### ISSUE TITLE
Received signal drifts from console reading

### ISSUE THREAD

**Issue by ar0berts** [lheijst/weewx-rtld#12]
Hi,
I am puzzled by the behaviour of rtldavis packets. over a 24  hour period they drift away from the packets received by the console. The set up is ubuntu 20.04 LTS with a debian type installation of weewx 4.6.1 and a standard Realtek dongle with an aerial next to the Davis console. The ISS is a Vantage Vue 6250.

lsusb: Bus 003 Device 073: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T

I attach a screenshot of the weewx html report 10 minutes after a reset showing changes in humidity, temperature wind direction. The barometer and inTemp come in separately from a BMP280.
There are no other
Also a picture of the console just before the reset and syslog  before and after the reset. There are no houses (or weather stations anywhere near me ~1km so I can't think that I'm picking up another weather station.

I hope there is a simple explanation - help and advice humbly received!
Andrew
![Davis Console 01-Mar-2022](https://user-images.githubusercontent.com/2455814/156121839-785e06b2-4880-4214-a584-930574904867.jpg)
[March-01-2022.txt](https://github.com/lheijst/weewx-rtldavis/files/8159456/March-01-2022.txt)
[rtldavis_weewx-conf.txt](https://github.com/lheijst/weewx-rtldavis/files/8159457/rtldavis_weewx-conf.txt)
![Screenshot_weewx](https://user-images.githubusercontent.com/2455814/156121854-7cc8a46a-8bdc-44a0-892e-408943403385.png)

**Comment by lheijst** [comment]
Hi Andrew,

Looking at the syslog my first thoughs are the program is receiving packets from more than one ISS station. To be sure I need more syslog data: a few hours before a reset followed by a few hours after the reset would be fine to be sure.

Best regards,
Luc Heijst

Verstuurd vanaf mijn iPad

**Comment by ar0berts** [comment]
Will do Luc. Give me a couple of days and I will get back to you.

Many thanks,

Andrew

On 1 March 2022 09:59:24 GMT, Luc Heijst ***@***.***> wrote:
>Hi Andrew,
>
>
>
>Looking at the syslog my first thoughs are the program is receiving packets from more than one ISS station. To be sure I need more syslog data: a few hours before a reset followed by a few hours after the reset would be fine to be sure.
>
>
>
>Best regards,
>
>Luc Heijst
>
>
>
>Verstuurd vanaf mijn iPad
>
>
>
>> Op 1 mrt. 2022 om 04:10 heeft Andrew Roberts ***@***.***> het volgende geschreven:
>
>> >
>> ﻿
>
>> Hi,
>
>> I am puzzled by the behaviour of rtldavis packets. over a 24 hour period they drift away from the packets received by the console. The set up is ubuntu 20.04 LTS with a debian type installation of weewx 4.6.1 and a standard Realtek dongle with an aerial next to the Davis console. The ISS is a Vantage Vue 6250.
>
>> >
>> lsusb: Bus 003 Device 073: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
>
>> >
>> I attach a screenshot of the weewx html report 10 minutes after a reset showing changes in humidity, temperature wind direction. The barometer and inTemp come in separately from a BMP280.
>
>> There are no other
>
>> Also a picture of the console just before the reset and syslog before and after the reset. There are no houses (or weather stations anywhere near me ~1km so I can't think that I'm picking up another weather station.
>
>> >
>> I hope there is a simple explanation - help and advice humbly received!
>
>> Andrew
>
>> >
>> March-01-2022.txt
>
>> rtldavis_weewx-conf.txt
>
>> >
>> >
>> —
>
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>
>> Triage notifications on the go with GitHub Mobile for iOS or Android. >
>> You are receiving this because you are subscribed to this thread.
>
>
>
>
>
>-- >
>Reply to this email directly or view it on GitHub:
>
>https://github.com/lheijst/weewx-rtldavis/issues/12#issuecomment-1055246056
>
>You are receiving this because you authored the thread.
>
>
>
>Message ID: ***@***.***>
-- 
M: 07837 302615

**Comment by ar0berts** [comment]
Luc, I am 99% certain you are right about another Davis Vantage ISS in my locality.

I have three sets of data:

First a syslog where the console and the rtldavis stanza in weewx.conf are set at ID=1 . I manually [changed the ISS ID](https://www.google.com/search?q=set+the+id+of+a+davis+vantage+vue+iss&oq=set+the+id+of+a+davis+vantage+vue+iss&aqs=chrome..69i57j33i160l2.15803j0j4&sourceid=chrome&ie=UTF-8#kpvalbx=_gBMfYufwOMWX8gLthIDIBA21) part way into the logging at 15.09 hrs to ID=7. This caused the console to show no ISS data but the cheap RTL dongle carries on looking at channel 1.
[syslog_channelHop_4-3-2022.txt](https://github.com/lheijst/weewx-rtldavis/files/8190951/syslog_channelHop_4-3-2022.txt)

The second data set is a syslog with the console, rtldavis and the ISS set to an ID=1 with a hard restart of weewx part way through
[syslog_5-3-2022_Restart_Weewx.txt](https://github.com/lheijst/weewx-rtldavis/files/8190950/syslog_5-3-2022_Restart_Weewx.txt)

Finally a syslog with the console, rtldavis and the ISS set to an ID=7. The console agrees with the pkts :-)
[Syslog_All_Set_to_ID-7.txt](https://github.com/lheijst/weewx-rtldavis/files/8190948/Syslog_All_Set_to_ID-7.txt)

I will track the station and weewx over the next few days and then close the issue. The learning point is that the RTL dongles are very sensitive and can track a station a long way away.

A final mystery in the data is 'hail' and 'hailRate' packets - the ISS manual doesn't mention such a sensor.

Thanks for sorting this out.

Andrew
